---
heat_template_version: 2016-10-14
resources:
  demo_network:
    type: OS::Neutron::Net
  demo_subnet:
    type: OS::Neutron::Subnet
    properties:
      network: { get_resource: demo_network }
      cidr: 192.168.101.0/24
      dns_nameservers:
        - 8.8.4.4
        - 8.8.8.8
  demo_subnet_port:
    type: OS::Neutron::Port
    properties:
      network: { get_resource: demo_network }
      fixed_ips:
        - subnet_id: { get_resource: demo_subnet }
      security_groups:
        - open
  demo_router:
    type: OS::Neutron::Router
    properties:
      external_gateway_info:
        network: external_network
  external_router_interface:
    type: OS::Neutron::RouterInterface
    properties:
      router: { get_resource: demo_router }
      subnet: { get_resource: demo_subnet }
  demo_instance:
    type: OS::Nova::Server
    properties:
      flavor: m1.tiny
      image: CirrOS
      networks:
        - port: { get_resource: demo_subnet_port }
  demo_floating_ip:
    type: OS::Neutron::FloatingIP
    properties:
      floating_network: external_network
  demo_floating_ip_association:
    type: OS::Nova::FloatingIPAssociation
    properties:
      floating_ip: { get_resource: demo_floating_ip }
      server_id: { get_resource: demo_instance }
